# HikariCP
spring:
  datasource:
    username: LCCS019999
    password: aaaaaa
    url: jdbc:oracle:thin:@10.110.85.135:1521/orcl
    driverClassName: oracle.jdbc.OracleDriver

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.etoak.entity

# log
logging:
  level:
    com:
      etoak: debug
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: "*"

---

#*********Eureka Client Provider1 Config begin*********
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: service-provider-node1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
#*********Eureka Client Provider1 Config end*********
---
#*********Eureka Client Provider1 Config begin*********
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: service-provider-node2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
#*********Eureka Client Provider1 Config end*********