#*********通用配置 begin*********
# HikariCP
spring:
  datasource:
    username: 用户名
    password: 密码
    url: jdbc:oracle:thin:@IP:1521/orcl
    driverClassName: oracle.jdbc.OracleDriver

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.etoak.entity

# log
logging:
  level:
    com:
      etoak: debug

eureka:
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: info,health,refresh
      cors:
        allowed-methods: GET,POST

info:
  app:
    name: ${spring.application.name}
  company:
    name: www.etoak.com
#  build:
#    artifactId: @project.artifactId@
#    version: @project.version@


myapp:
  test:
    msg: 测试修改后1
    sleepTime: 8000
#*********通用配置 end*********


---


#*********服务提供者node1配置 begin*********
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: node1

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
#*********服务提供者node1配置 end*********


---


#*********服务提供者node2配置 begin*********
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: node2

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
#*********服务提供者node2配置 end*********